# Top-level NixOS module for p1g8 (Lenovo ThinkPad P1 Gen 8).
# Counterpart of p1/configuration.nix for the new parallel host.
#
# Wiring: shared laptop.nix's `nix.nixPath` resolves `nixos-config` to
# this file via `config.lib._custom_.name = "p1g8"` (set in p1g8.nix).
# There is no flake — the channel-based path is the only mechanism.
#
# See install-plan §1c for the import-list rationale.
{ config, pkgs, ... }:

let
  ndtSources = import ../ndt/sources.nix { };
in
{
  imports = [
    ../nixos-shared/packages/kanata/service.nix
    # disko provides the schema for ./disko.nix and synthesises
    # `fileSystems` / `boot.initrd.luks.devices` at switch time.
    # That is what makes `nixos-generate-config --no-filesystems` safe.
    # Subpath verified: ${disko}/module.nix exists in the tracked rev.
    (import "${ndtSources.disko.outPath}/module.nix")
    ./disko.nix
    ./hardware-configuration.nix          # generated by `nixos-generate-config --no-filesystems` on the live ISO
    ../laptop/laptop.nix
    ./p1g8.nix                            # host-overrides; replaces p1/p1.nix
    ../p1/globalprotect/default.nix       # reuse p1's globalprotect — same VPN config
    (import ../nixos-shared/wireguard.nix "p1g8")  # per-host WG (§1d-1); needs mozwire bundle in secrets.nix
  ];

  # Mirror p1's setup — sudo-with-insults pulled from the p1 dir
  # (only place it lives in this repo).
  security.sudo.package = pkgs.callPackage ../p1/sudo-custom.nix { };

  hardware.graphics.extraPackages = with pkgs; [
    intel-compute-runtime
  ];
}
