# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# `fileSystems` and `swapDevices` are deliberately absent since the
# 2026-09-06 HDD -> SSD migration: ./disko.nix synthesises both. Regenerate
# with `nixos-generate-config --no-filesystems`, as on p1g8.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # "nvme" added 2026-09-06: root moved from the SATA HDD to an M.2 NVMe.
  # The rest of this list is the 2018 scan, when the box was SATA-only --
  # without the module the initrd cannot find its root and drops to the
  # emergency shell. "ahci"/"sd_mod" stay: the old HDD and the three
  # external drives are still attached.
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  nix.settings.max-jobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
